# Parses the stripped poe2wiki "List of modifiers for tablets" text dump
# (C:\Temp\tablets_wiki.txt) and generates TabletMods.cs with raw mod data.
param(
    [string]$InputFile  = "C:\Temp\tablets_wiki.txt",
    [string]$OutputFile = "$PSScriptRoot\..\Poe2Crafter.Core\Data\TabletMods.cs"
)

$lines = Get-Content $InputFile | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }

$tabletNames = 'Irradiated','Abyss','Breach','Delirium','Expedition','Overseer','Ritual','Temple'
$tablet  = $null
$modType = $null
$group   = $null
$rows    = New-Object System.Collections.Generic.List[object]

for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]

    if ($line -match '^(Irradiated|Abyss|Breach|Delirium|Expedition|Overseer|Ritual|Temple) tablet$') {
        $tablet = $Matches[1]; continue
    }
    if ($line -eq 'Prefixes')  { $modType = 'Prefix';  continue }
    if ($line -eq 'Suffixes')  { $modType = 'Suffix';  continue }
    if ($line -match '^Group:\s*(.+)$') { $group = $Matches[1].Trim(); continue }

    # Column header sequence "Modifier / iLvl / Stats / Tags" precedes one or more data rows:
    # <affix name>, <ilvl number>, <stat text>
    if ($line -eq 'Modifier' -and $i + 3 -lt $lines.Count -and
        $lines[$i+1] -eq 'iLvl' -and $lines[$i+2] -eq 'Stats' -and $lines[$i+3] -eq 'Tags') {
        $j = $i + 4
        while ($j + 2 -lt $lines.Count -and $lines[$j+1] -match '^\d+$') {
            if (-not $tablet -or -not $modType -or -not $group) { break }
            $rows.Add([pscustomobject]@{
                Tablet = $tablet; ModType = $modType; Group = $group
                Affix  = $lines[$j]; Ilvl = [int]$lines[$j+1]; Template = $lines[$j+2]
            })
            $j += 3
            # stop if next line starts a new structure
            if ($j -ge $lines.Count) { break }
            if ($lines[$j] -match '^(Group:|Prefixes$|Suffixes$|Modifier$)' -or
                $lines[$j] -match ' tablet$') { break }
        }
        $i = $j - 1
        continue
    }
}

Write-Output "Parsed $($rows.Count) tablet mod rows"
$rows | Group-Object Tablet | ForEach-Object { Write-Output "  $($_.Name): $($_.Count)" }

# Tablets have no tier ladders (all ilvl 1); groups that contain several distinct
# mods are split into one group per mod (group + affix slug) so the in-game
# annotation tier (always 1) always matches.
$entries = New-Object System.Collections.Generic.List[string]
# Expedition tablets are not in the current patch — wiki data is stale there
$rows = $rows | Where-Object { $_.Tablet -ne 'Expedition' }
foreach ($r in $rows) {
    $tag  = "tablet_$($r.Tablet.ToLower())"
    $slug = ($r.Affix -replace "[^A-Za-z]", '')
    $grp  = "$($r.Group)_$slug"
    $tpl  = $r.Template -replace '"', '\"'
    $afx  = $r.Affix -replace '"', '\"'
    $entries.Add("        (`"$tag`", `"$($r.ModType)`", `"$grp`", `"$afx`", 1, $($r.Ilvl), `"$tpl`"),")
}

$cs = @"
// <auto-generated>
// Generated by tools/Generate-TabletMods.ps1 from poe2wiki "List of modifiers for tablets".
// Tablet mod pools are not present in PoB2 data, hence this embedded copy.
// </auto-generated>
using Poe2Crafter.Core.Models;
using Poe2Crafter.Core.Parsing;

namespace Poe2Crafter.Core.Data;

public static class TabletMods
{
    private static readonly (string Tag, string ModType, string Group, string Affix, int Tier, int Ilvl, string Template)[] Raw =
    {
$($entries -join "`n")
    };

    public static IReadOnlyList<ModDefinition> All { get; } = Raw
        .Select(r =>
        {
            var (vMin, vMax) = PobModParser.ExtractRanges(r.Template);
            return new ModDefinition
            {
                Id         = `$"{r.Group}_{r.Tag}_{r.Tier}",
                Type       = r.ModType,
                AffixName  = r.Affix,
                Template   = r.Template,
                Templates  = [r.Template],
                MatchRegex = PobModParser.BuildMatchRegex(r.Template),
                Group      = r.Group,
                Tier       = r.Tier,
                MinLevel   = r.Ilvl,
                Source     = "tablet",
                ValuesMin  = vMin,
                ValuesMax  = vMax,
                ItemTags   = [r.Tag],
            };
        })
        .ToList();
}
"@

New-Item -ItemType Directory -Force (Split-Path $OutputFile) | Out-Null
$cs | Out-File $OutputFile -Encoding utf8
Write-Output "Written: $OutputFile"
